function [VT_adder,dlt,dlc] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [VT_adder,dlt,dlc] = IMPORTFILE(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   [VT_adder,dlt,dlc] = IMPORTFILE(FILE,SHEET) reads from the specified
%   worksheet.
%
%   [VT_adder,dlt,dlc] = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from
%   the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.%
% Example:
%   [VT_adder,dlt,dlc] = importfile('TILT_analysis_wFB_100mV _exp_WL0.8.xlsx','tt25',3,114);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2022/03/10 15:06:50

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 3;
    endRow = 114;
end

%% Import the data
data = [xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(1),endRow(1))),...
    xlsread(workbookFile, sheetName, sprintf('H%d:I%d',startRow(1),endRow(1)))];
for block=2:length(startRow)
    tmpDataBlock = [xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(block),endRow(block))),...
        xlsread(workbookFile, sheetName, sprintf('H%d:I%d',startRow(block),endRow(block)))];
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
VT_adder = data(:,1);
dlt = data(:,2);
dlc = data(:,3);

